spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${PGSQL_HOST:localhost}:5432/todo_database2
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
rownskx:
  app:
    jwtSecret: ======================RownSkx=Spring===========================
    jwtExpirationMs: 86400000
  # security:
  #   oauth2:
  #     client:
  #       registration:
  #         google:
  #           client-id: ${OAUTH2_CLIENT_ID}
  #           client-secret: ${OAUTH2_CLIENT_SECRET}
  #           redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
# logging:
#     level:
#         org:
#             springframework:
#                 security: TRACE
